name: ml-app
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - opencv=4.7.0
  - pip=23.0.1
  - python=3.11.3
  - pytorch=2.0.0
  - streamlit=1.9.0
  - transformers=4.27.4
  - pip:
    - streamlit-drawable-canvas==0.9.2
