name: ml-app
channels:
  - conda-forge
dependencies:
  - pytorch
  - transformers
  - python=3.10.4
  - pip=21.2.4
  - pip:
    - opencv-python==4.6.0.66
    - streamlit==1.10.0
    - streamlit-drawable-canvas==0.9.1
